### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by aknuds1**
Fix one failing test.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
wait, but weren't the tests already passing? - lil bit confused hah

**Comment by aknuds1** [comment]
@yoshuawuyts It fails for me locally at least:

    # should capture link click
    ok 9 should be equal
    ok 10 should be equal
    not ok 11 should be equivalent
      ---
        operator: deepEqual
        expected: |-
          { hash: undefined, href: 'someUrl#', pathname: 'someUrl', search: undefined }
        actual: |-
          { hash: undefined, href: 'someUrl#', pathname: 'someUrl', search: {} }
        at: Test.t.test (/Users/arve/Projects/sheet-router/test/href.js:57:7)
      ...

**Comment by aknuds1** [comment]
@yoshuawuyts On that subject, seems as if `test:cov` does way fewer tests than `test`? Any idea why?

**Comment by yoshuawuyts** [comment]
Uehhhh, your guess is as good as mine - afk rn

**Comment by ungoldman** [comment]
Can confirm this test is failing for me locally as well. Not sure why.

```
not ok 13 should be equivalent
  ---
    operator: deepEqual
    expected: |-
      { hash: undefined, href: 'someUrl#', pathname: 'someUrl', search: undefined }
    actual: |-
      { hash: undefined, href: 'someUrl#', pathname: 'someUrl', search: {} }
    at: Test.t.test (/Users/ng/dev/git/sheet-router/test/href.js:57:7)
  ...
```

**Comment by aknuds1** [comment]
The thing is only a subset of tests is being executed under Travis by the
test:cov command. I don't know why this is.

**Comment by yoshuawuyts** [comment]
Thanks!

**Pull request merged**
