### PR TITLE
chore(router): fix route match regex

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Related to https://github.com/yoshuawuyts/choo/pull/279
Fixes the routing regex to also include ports. Thanks!

cc/ @sethvincent

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
fixed the tests

**Comment by yoshuawuyts** [comment]
or... did I?

**Comment by yoshuawuyts** [comment]
ok yeah tests fixed - added out of the box electron support because why not, it's only 3 more lines

**Comment by yoshuawuyts** [comment]
cc/ @zeke not sure, but feel out-of-the-box electron support landing might in a way be relevant to your interests C:

**Comment by zeke** [comment]
Is this related to https://github.com/hypermodules/choo-location-electron ?

cc @bcomnes @ungoldman @sethvincent

**Comment by bcomnes** [comment]
Oh cool. Will check it out when I get back from lunch.

**Comment by bcomnes** [comment]
Yeah this is what we have to do:
https://github.com/hypermodules/choo-location-electron/blob/master/index.js

Do you not need to remove the `file://` like we do?

**Comment by ungoldman** [comment]
Yeah `choo-location-electron` is a pretty aggressive monkey patch. It adds a subscription that intercepts all clicks and removes the file protocol prefix from any anchor tag with an href that's been clicked. I don't think this PR deals with the file protocol issue.

**Comment by yoshuawuyts** [comment]
ohh, don't recall seeing that package yet - feels like I should've.
Definitely related. Think it would make it so that all path handling is
being taken
care of by `choo`, and the only thing left would be to have href handlers
also open
links externally. Does that sound right?

**Comment by bcomnes** [comment]
Sounds right to me.

**Comment by ungoldman** [comment]
for reference it's something @sethvincent wrote in [adventuretron/app/models/location.js#L25](https://github.com/adventuretron/adventuretron/blob/c09a20cffb09650ce11f0195c150aaba13a9f45b/app/models/location.js#L25) that @bcomnes generalized for use in other electron apps in `choo-location-electron`. definitely would be nice for it to be handled more elegantly inside choo proper if you think it's not beyond the purview of choo's responsibilities @yoshuawuyts 😁

**Comment by yoshuawuyts** [comment]
@bcomnes yeah so we remove it here https://github.com/yoshuawuyts/sheet-router/pull/57/files#diff-f58117fccf15a73590aec25c3b241b3aR2

---

The only bits left after this would then be to handle `href` links in a certain way - in the case of `electron` use their [shell.openExternal()](https://github.com/hypermodules/choo-location-electron/blob/master/index.js#L31) call for example - perhaps an extra hook on `choo` to handle this? - not sure; feel like we've got a whole slew of plugins already and like having one more feels a lil bit gross haha - but then again so would a model soooo; idk haha

---
anyway, releasing this as a minor release :sparkles:

**Comment by yoshuawuyts** [comment]
`v4.1.0` :sparkles:

**Pull request merged**
